### ISSUE TITLE
trying to convert huggingface whisper model to pytorch

### ISSUE THREAD

**Issue by nullonesix** [pytorch-labs/gpt-fast#189]
i used the converter here:

https://github.com/pytorch-labs/gpt-fast/blob/main/scripts/convert_hf_checkpoint.py

but i get this error when trying to convert my huggingface checkpoint:

```
swarms@dpm4:~/gpt-fast/scripts$ python3 converthf_checkpoint.py --checkpoint_dir /home/swarms/checkpoint-4000/ --model
name large-v3
Traceback (most recent call last):
  File "/home/swarms/gpt-fast/scripts/convert_hf_checkpoint.py", line 132, in <module>
    convert_hf_checkpoint(
  File "/home/swarms/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, kwargs)
  File "/home/swarms/gpt-fast/scripts/convert_hf_checkpoint.py", line 31, in convert_hf_checkpoint
    config = ModelArgs.from_name(model_name)
  File "/home/swarms/gpt-fast/model.py", line 55, in from_name
    return cls(transformer_configs[config[0]])
IndexError: list index out of range
```

**Comment by yanboliang** [comment]
We only support transformer based models, check the list of model we supported at:
https://github.com/pytorch-labs/gpt-fast/blob/c9f683edd4f89d3e81ed8f52387e866a245e3226/model.py#L60
