### ISSUE TITLE
Compatible with AutoGPTQ?

### ISSUE THREAD

**Issue by yhyu13** [pytorch-labs/gpt-fast#20]
Hi,

Does the GPTQ converted models the same as AutoGPTQ? Do they  share the same configuration settting such as group size actor order and such?

There are plenty of GPTQ models out ther on hf already that could potentially benifit from this repo already!

Thanks

cc @TheBloke @PanQiWei

**Comment by cwsappeal** [comment]
Test 

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2FQh6NZWsFx1G1O%2Fgiphy.gif&token=awesome" data-gitmeme-token="awesome"><img src="https://media1.giphy.com/media/Qh6NZWsFx1G1O/giphy.gif" title="Created by gitme.me with /awesome"
        alt="awesome"/></a>

**Comment by TheBloke** [comment]
Great to hear!

**Comment by zhangp365** [comment]
> Act-order can be easily supported using the same trick of exllama. I did a few test converting off-the-shelf GPTQ models to gpt-fast format using [sample code here](https://github.com/pytorch-labs/gpt-fast/compare/main...chu-tianxiang:gpt-fast:main) `python convert_hf_checkpoint.py --checkpoint_dir Llama-2-7B-GPTQ --model_name llama-7B` and got 193 tokens/s in single A100 which is really impressive.

I used the convert_hf_checkpoint script, but got the below exception:
```
Model config {'block_size': 2048, 'vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'dim': 4096, 'intermediate_size': 11008, 'n_local_heads': 32, 'head_dim': 128, 'rope_base': 10000, 'norm_eps': 1e-05}
Traceback (most recent call last):
  File "D:\llm\gpt_fast_fork\myvenv\lib\site-packages\torch\_ops.py", line 757, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator aten::_convert_weight_to_int4pack

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\llm\gpt_fast_fork\gpt-fast\scripts\convert_hf_checkpoint.py", line 174, in <module>
    convert_hf_checkpoint(
  File "D:\llm\gpt_fast_fork\myvenv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\llm\gpt_fast_fork\gpt-fast\scripts\convert_hf_checkpoint.py", line 152, in convert_hf_checkpoint
    weight_int4pack = torch.ops.aten._convert_weight_to_int4pack(weight_int32.cuda(), inner_k_tiles).to('cpu')
  File "D:\llm\gpt_fast_fork\myvenv\lib\site-packages\torch\_ops.py", line 761, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'aten' object has no attribute '_convert_weight_to_int4pack'
```
I have installed the newest torch of 2.1.1, It's the same. How can I fix that? Thank you.
