### ISSUE TITLE
Unexpected key(s) in state_dict: "rope.freqs". 

### ISSUE THREAD

**Issue by Prakash19921206** [pytorch-labs/gpt-fast#42]
Hi all,
i tried to run `generate.py` with following command line parameters 
`--compile --checkpoint_path llama/llama-2-7b-chat/consolidated.00.pth --prompt "Hello, my name is"`
Got below output/ error

>Loading model ... 
> Traceback (most recent call last):
>   File "generate.py", line 407, in <module>
>     main(
>   File "generate.py", line 275, in main
>     model = _load_model(checkpoint_path, device, precision, use_tp)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "generate.py", line 226, in _load_model
>     model.load_state_dict(checkpoint, assign=True)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for Transformer:
> 	Unexpected key(s) in state_dict: "rope.freqs". 
> python-BaseException

Process finished with exit code 1

I know that rope.freqs is present in pth file but what value should i add in `model.py` under **transformer_configs** dict?
Thanks

**Comment by way-how** [comment]
I am facing the same issue. Are there any updates on this?
