### ISSUE TITLE
AssertionError: assert model_map_json.is_file()

### ISSUE THREAD

**Issue by S-Yacer** [pytorch-labs/gpt-fast#95]
when trying to convert weights of the mistralai/Mixtral-8x7B-Instruct-v0.1 or any other finetuned mixtral model, I run into the error below. But when converting weights of the mistralai/Mixtral-8x7B-v0.1, it works just fine... why is that ? can anyone help please.

`Model config {'block_size': 2048, 'vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'dim': 4096, 'intermediate_size': 11008, 'n_local_heads': 32, 'head_dim': 128, 'rope_base': 10000, 'norm_eps': 1e-05, 'moe': False, 'num_experts': 8, 'num_activated_experts': 2}
Traceback (most recent call last):
  File "/home/paperspace/gpt-fast/scripts/convert_hf_checkpoint.py", line 181, in <module>
    convert_hf_checkpoint(
  File "/home/paperspace/gpt-fast/scripts/convert_hf_checkpoint.py", line 171, in convert_hf_checkpoint
    return convert_hf_checkpoint_llama(checkpoint_dir=checkpoint_dir, model_name=model_name)
  File "/home/paperspace/gpt-fast/gptfast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/paperspace/gpt-fast/scripts/convert_hf_checkpoint.py", line 34, in convert_hf_checkpoint_llama
    assert model_map_json.is_file()
AssertionError`

**Comment by S-Yacer** [comment]
https://github.com/pytorch-labs/gpt-fast/pull/60
